#include "device_not_editable/driverlib.h"
#include "include_editable/pinmux.h"

void GPIO_setPinMuxConfig(void)
{
    uint32_t lockValA;
    uint32_t lockValB;
    uint32_t lockValC;
    uint32_t lockValD;
    uint32_t lockValE;
    uint32_t lockValF;

    EALLOW;

    //
    // Save the current value of the GPIO lock registers
    //
    lockValA = HWREG(GPIOCTRL_BASE + GPIO_O_GPALOCK);
    lockValB = HWREG(GPIOCTRL_BASE + GPIO_O_GPBLOCK);
    lockValC = HWREG(GPIOCTRL_BASE + GPIO_O_GPCLOCK);
    lockValD = HWREG(GPIOCTRL_BASE + GPIO_O_GPDLOCK);
    lockValE = HWREG(GPIOCTRL_BASE + GPIO_O_GPELOCK);
    lockValF = HWREG(GPIOCTRL_BASE + GPIO_O_GPFLOCK);

    //
    // Unlock the GPIO control registers
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPALOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBLOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCLOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDLOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPELOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPFLOCK) = 0x00000000;

    //
    // Clear the mux register fields that are about to be changed
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX1) &= ~GPAMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX2) &= ~GPAMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX1) &= ~GPAMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX2) &= ~GPAMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX1) &= ~GPBMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX2) &= ~GPBMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX1) &= ~GPBMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX2) &= ~GPBMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX1) &= ~GPCMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX2) &= ~GPCMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX1) &= ~GPCMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX2) &= ~GPCMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDGMUX1) &= ~GPDMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDGMUX2) &= ~GPDMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDMUX1) &= ~GPDMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDMUX2) &= ~GPDMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEGMUX1) &= ~GPEMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEGMUX2) &= ~GPEMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEMUX1) &= ~GPEMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEMUX2) &= ~GPEMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPFGMUX1) &= ~GPFMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPFMUX1) &= ~GPFMUX1_MASK;

    //
    // Write pin muxing to mux registers
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX1) |= GPAGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX2) |= GPAGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX1) |= GPAMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX2) |= GPAMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX1) |= GPBGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX2) |= GPBGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX1) |= GPBMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX2) |= GPBMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX1) |= GPCGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX2) |= GPCGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX1) |= GPCMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX2) |= GPCMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDGMUX1) |= GPDGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDGMUX2) |= GPDGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDMUX1) |= GPDMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDMUX2) |= GPDMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEGMUX1) |= GPEGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEGMUX2) |= GPEGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEMUX1) |= GPEMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPEMUX2) |= GPEMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPFGMUX1) |= GPFGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPFMUX1) |= GPFMUX1_VALUE;

    //
    // Write pin analog mode select to registers
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBAMSEL) &= ~GPBAMSEL_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBAMSEL) |= GPBAMSEL_VALUE;

    //
    // Write Input X-BAR pin selection to registers
    //
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT1SELECT) = INPUT1SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT2SELECT) = INPUT2SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT3SELECT) = INPUT3SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT4SELECT) = INPUT4SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT5SELECT) = INPUT5SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT6SELECT) = INPUT6SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT7SELECT) = INPUT7SELECT_VALUE;
    HWREGH(XBAR_INPUT_BASE + XBAR_O_INPUT8SELECT) = INPUT8SELECT_VALUE;

    //
    // Restore GPIO lock register values
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPALOCK) = lockValA;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBLOCK) = lockValB;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCLOCK) = lockValC;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDLOCK) = lockValD;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPELOCK) = lockValE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPFLOCK) = lockValF;

    EDIS;
}
